services:
  db:
    image: mysql:8.0.30  # MySQL service
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: fhir_data
      MYSQL_USER: fhiruser
      MYSQL_PASSWORD: fhirpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  app:
    build: .
    container_name: python_app
    command: ["./wait-for-it.sh", "db:3306", "--", "python", "main.py"]
    volumes:
      - .:/app
    depends_on:
      - db  # Ensures that the db service starts before the app
    networks:
      - app-network
    environment:
      DATABASE_URL: mysql+pymysql://fhiruser:fhirpassword@db:3306/fhir_data

volumes:
  mysql_data:  # Persistent storage for MySQL

networks:
  app-network:  # Custom network for both services
    driver: bridge
